### ISSUE TITLE
[BUG] with this modul active - no status effect icons displayed on Token anymore (except from Encumberance module)

### ISSUE THREAD

**Issue by R0TEAM** [p4535992/foundryvtt-active-effect-manager-lib#1]
**Module Version:** v0.0.7

**Describe the bug**
if this module is active - no status icon on tokens is more shown from the default status icon menue from the token

**To Reproduce**
1. click on token and select him
2. open with RMB on Token the token info buttons
3. select status change - enebla any status here
4. the token change his status - but no info icon is shown on the token

**Expected behavior**
a info token should appear on the token

**Screenshots**

**Browser:**
 - 

**Foundry Version:** 
9.269
**Game System:** 
DND5e
**Additional context**
Add any other context (like other modules installed) about the problem here.

**Comment by p4535992** [comment]
@R0TEAM any error on the web console (click f12 on the browser)

**Comment by R0TEAM** [comment]
if i set an status (no status icon visible) amd force redraw (strg-F5) i get this error on screen :
"Canvas Drawing Failed for the Token Layer"
and this in the F12 log:
foundry.js:319 TypeError: Cannot read properties of undefined (reading 'split')
[Detected 4 packages: active-effect-manager-lib, lib-wrapper, statuscounter, perfect-vision]
    at fromUuid (foundry.js:2540)
    at Token5e.drawShyEffects (lib.js:370)
    at Wrapper.🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:595)
    at Token5e.🎁Token.prototype.drawEffects#statuscounter (rendering.js:11)
    at Wrapper.🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:620)
    at Token5e.🎁Token.prototype.drawEffects#0 (libWrapper-wrapper.js:189)
    at Token5e.draw (foundry.js:37975)
    at async Promise.all (index 0)
    at async TokenLayer.draw (foundry.js:22266)
    at async Canvas.draw (foundry.js:20116)
    at async Canvas.🎁Canvas.prototype.draw#perfect-vision (canvas.js:415)
    at async Scene.view (foundry.js:17859)
    at async Game.initializeCanvas (foundry.js:5677)
    at async Game.setupGame (foundry.js:5548)
    at async Game._initializeGameView (foundry.js:6514)
    at async Game.initialize (foundry.js:5431)

**Comment by p4535992** [comment]
@R0TEAM  It's seem a module conflict with "status icon" or "perfect vision" try to disable the "Enable Shy Effect Icons" feature from the module settings of the module

**Comment by R0TEAM** [comment]
unlikely - as even without PerfectVision and/or StatuseffectIcon modules active i get "no" status effect icon with library:active-effect-manager

**Comment by R0TEAM** [comment]
and i can set watever option combo is possible in the modul settings - the result is always the same > no Icons ...
and with an status active (except encumbarance module) after an redraw massive errors in Token handling - so ATM not usable this library and all depended module

**Comment by p4535992** [comment]
@R0TEAM Very Sorry for all the trouble. I have tested and is  working fine in all my worlds.
https://i.imgur.com/nPcjYXy.gif

![gif](https://i.imgur.com/nPcjYXy.gif)

At this point I can only ask you some more focused questions:

- After disabled PV and StatuseffectIcon are you still getting the same error caused from `Token5e.drawShyEffects` ?
- Is happening only with one token in a specific world ? or for all the tokens in different worlds ?
- What browser are you using ?
- Did you have the module "Shy Effects" by Kandashi active by any chance ?

**Comment by R0TEAM** [comment]
problen not bound to an token or world (at last 2 diff world testet - diff scenes - 8~9 tokens)
i use the engine self - no browser on my side
have not shy effects ....
will try to make an informative video .... stay tuned :P

**Comment by R0TEAM** [comment]
here > https://youtu.be/tSTquyrYeCY

**Comment by R0TEAM** [comment]
oh - and btw. - i play in German ..... maybe this make a diff ??
