### ISSUE TITLE
[BUG] Conflict with Skills in D&D 5e

### ISSUE THREAD

**Issue by igorteuri** [p4535992/foundryvtt-active-effect-manager-lib#2]
![image](https://user-images.githubusercontent.com/64547748/183316556-bdd10e13-0930-482a-9413-5151141bf027.png)

![image](https://user-images.githubusercontent.com/64547748/183316600-e11e532f-0d35-4e1a-bd82-eb64cb7731f8.png)

When using the Module, all Skill checks doesn't select the proper attribute. The rolling windows always selects Strenght

![image](https://user-images.githubusercontent.com/64547748/183316788-e82fbd12-caf0-43ff-be9a-a0ed4e9e547a.png)

Used the Find the Culprit in order to find that the issue was with this module.
![image](https://user-images.githubusercontent.com/64547748/183316805-cd318d7a-a793-4545-9deb-d1dfc022427c.png)

**Comment by p4535992** [comment]
Sorry can't replicate, make test in many worlds, maybe is some module conflict ? Have you tried in a world with only this module active ? 
https://i.imgur.com/kmC7Hb0.gif
![IMG45](https://i.imgur.com/kmC7Hb0.gif)

**Comment by p4535992** [comment]
i finally replicate and solved the issue !!
