### ISSUE TITLE
[BUG] Shy Effects breaking canvas drawing

### ISSUE THREAD

**Issue by OmnesPotens** [p4535992/foundryvtt-active-effect-manager-lib#7]
**Module Version:** v0.1.24

**Describe the bug**
Shy Effects breaks Canvas drawing for Players

**To Reproduce**
1. Enable Shy Effects
2. Login to the game world as a Player
3. Observe Canvas grey-screen (fails to load)

**Expected behavior**
The Canvas should load properly and any active Scene that the Player has a Token on should be visible

**Screenshots**
![image](https://user-images.githubusercontent.com/21691862/213537325-c1484140-ba45-43f9-8363-8b7994990569.png)

**Browser:**
 - Chrome

**Foundry Version:** v10 build 291

**Game System:** dnd5e

**Additional context**
Logs:
[shy-effects-breaks-canvas.log](https://github.com/p4535992/foundryvtt-active-effect-manager-lib/files/10460230/shy-effects-breaks-canvas.log)

**Comment by p4535992** [comment]
I try to fix this on 0.2.0
